name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.20"
          python-version: "3.10"
      - name: Verify uv installation
        run: uv --version
      - name: Set up Python
        run: uv python install
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest Reason: get it running on ubuntu-latest first
          # - macOS-latest   Reason: get it running on ubuntu-latest first
        python-version: ["3.10",]
    name: Run tests
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.20"
          python-version: ${{ matrix.python-version }}
      - name: Verify uv installation
        run: uv --version
      - name: Set up Python
        run: uv python install
      - name: Install amici dependencies
        run: |
          sudo apt update
          sudo apt install -y swig
          sudo apt install -y libblas-dev
          sudo apt install -y libatlas-base-dev
          sudo apt install -y libhdf5-dev
      - name: Load cached venv
        id: cached-uv-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/uv.lock') }}
      - name: Install dependencies
        run: uv pip install -e .[sbml]
        if: steps.cached-uv-dependencies.outputs.cache-hit != 'true'
      - name: Prepare cpp test
        run: |
          sudo apt install -y cmake
          sudo apt install -y libeigen3-dev
          sudo ln -s /usr/include/eigen3/Eigen /usr/include/Eigen
          sudo apt install -y pybind11-dev
          source .\venv\bin\activate
          cd eulerpi/examples/cpp
          mkdir build
          cd build
          cmake ..
          make -j
      - name: Run pytest
        run: |
          source .\venv\bin\activate
          pytest -v
      # TODO: coverage run creates segmentation fault on Github ci, but not locally. Debug it
      # - name: Run coverage
      #   run: |
      #     source $VENV
      #     coverage run -m pytest -v
      #     coverage report
