name: Publish to PyPI
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.20"
      - name: Verify uv installation
        run: uv --version
      - name: Set up Python
        run: uv python install
      - name: Install amici dependencies
        run: |
          sudo apt update
          sudo apt install -y swig
          sudo apt install -y libblas-dev
          sudo apt install -y libatlas-base-dev
          sudo apt install -y libhdf5-dev
      - name: Load cached venv
        id: cached-uv-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/uv.lock') }}
      - name: Install dependencies
        run: uv pip install -e .[sbml]
        if: steps.cached-uv-dependencies.outputs.cache-hit != 'true'
      - name: Publish to PyPI
        env:
          UV_PUBLISH_USERNAME: __token__
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          uv publish --username $UV_PUBLISH_USERNAME --token $UV_PUBLISH_TOKEN
