name: Publish to PyPI
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.20"
          enable-cache: true
      - name: Set up Python
        run: uv python install
      - name: Install amici dependencies
        run: |
          sudo apt update
          sudo apt install -y swig
          sudo apt install -y libblas-dev
          sudo apt install -y libatlas-base-dev
          sudo apt install -y libhdf5-dev
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Publish to PyPI
        env:
          UV_PUBLISH_USERNAME: __token__
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          uv publish --username $UV_PUBLISH_USERNAME --token $UV_PUBLISH_TOKEN
